name: PlasmoRadio
version: '0.1'
main: org.ferrum.plasmoRadio.PlasmoRadio
api-version: 1.21

commands:
  test:
    description: "Управление радио"
    usage: /test
  anvil:
    description: "хухйху"
    usage: /anvil
  change:
    description: "da"

depend:
  - PlasmoVoice